FROM ubuntu:20.04

RUN sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list && cat /etc/apt/sources.list

# dependencies
RUN apt update -y && \
	DEBIAN_FRONTEND=noninteractive apt-get build-dep -y qemu-user && \ 
	DEBIAN_FRONTEND=noninteractive apt install -y \
	clang emacs curl \
	qemu-user git libglib2.0-dev libfdt-dev \
	libpixman-1-dev zlib1g-dev libcapstone-dev \
	strace cmake python3 libprotobuf-dev \
	libibverbs-dev libjpeg62-dev \
	libpng16-16 libjbig-dev \
	build-essential libtool-bin python3-dev \
	automake flex bison libglib2.0-dev \
	libpixman-1-dev \
	python3-setuptools llvm wget \
	llvm-dev g++ g++-multilib python3 \
	python3-pip lsb-release gcc \
	llvm cmake libc6 libstdc++6 \
	linux-libc-dev gcc-multilib \
	apt-transport-https libtool \
        libtool-bin wget \
        automake autoconf \
        bison git gdb dumb-init valgrind ninja-build \
	time xxd python3-pip && \
	apt clean && \
	rm -rf /var/lib/apt/lists/*


# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /root/fuzzolic
COPY pyproject.toml uv.lock ./

RUN uv venv && uv sync

ENV VIRTUAL_ENV=/root/fuzzolic/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN apt-get install -y openssh-server
COPY . .

# Build QEMU tracer
RUN cd tracer && mkdir build && cd build && ../configure --target-list=x86_64-linux-user && make -j 32 

# Build custom Z3
RUN cd solver && mkdir build && cd build && cmake .. && make -j 32

# Set environment vars for Z3
# ENV C_INCLUDE_PATH=/root/fuzzolic/solver/fuzzy-sat/fuzzolic-z3/build/dist/include
# ENV LIBRARY_PATH=/root/fuzzolic/solver/fuzzy-sat/fuzzolic-z3/build/dist/lib
# ENV LD_LIBRARY_PATH=/root/fuzzolic/solver/fuzzy-sat/fuzzolic-z3/build/dist/lib
# ENV BASH_ENV=/root/.bashrc
# RUN echo "export C_INCLUDE_PATH=/root/fuzzolic/solver/build/fuzzolic-z3/build/dist/include" >> $BASH_ENV
# RUN echo "export LIBRARY_PATH=/root/fuzzolic/solver/build/fuzzolic-z3/build/dist/lib" >> $BASH_ENV
# RUN echo "export LD_LIBRARY_PATH=/root/fuzzolic/solver/build/fuzzolic-z3/build/dist/lib" >> $BASH_ENV


# Build AFL++
# RUN cd utils && git clone https://github.com/AFLplusplus/AFLplusplus.git && \
# 	cd AFLplusplus && git checkout 2dac4e7 && \
# 	git apply ../afl-showmap.c.patch && \
# 	make -j `nproc` all && cd qemu_mode && ./build_qemu_support.sh
# ENV AFL_PATH=/root/fuzzolic/utils/AFLplusplus
# RUN echo "export AFL_PATH=/root/fuzzolic/utils/AFLplusplus" >> $BASH_ENV

# Build fuzzolic tests
RUN cd tests && make

CMD bash
